#!/bin/sh

[ -r /etc/sysconfig/i18n ] && . /etc/sysconfig/i18n
export LANG
export SYSFONT
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
if [[ -f ${HOME}/.vnc/passwd ]]; then
    echo "${vnc_password}" | vncpasswd -f > ${HOME}/.vnc/passwd
fi
