#!/bin/sh

echo 'start remove docker mega container.' | tee "${SYNOPKG_PKGDEST}/package/logs/all.log" "${SYNOPKG_PKGDEST}/package/logs/preuninst.log"

container_id=$(cat "/tmp/QTbgsVrmwePlule_id")
container_name=$(docker ps --filter "id=${container_id}" --format "{{.Names}}")

docker stop -t 0 $container_id 2>&1 | tee "${SYNOPKG_PKGDEST}/package/logs/all.log" "${SYNOPKG_PKGDEST}/package/logs/preuninst.log"
docker rm -f $container_id 2>&1 | tee "${SYNOPKG_PKGDEST}/package/logs/all.log" "${SYNOPKG_PKGDEST}/package/logs/preuninst.log"

ret=$?

if [ -f "/usr/local/etc/services.d/docker_${container_name}.sc" ]; then
    echo "/usr/local/etc/services.d/docker_${container_name}.sc removed" | tee "${SYNOPKG_PKGDEST}/package/logs/all.log" "${SYNOPKG_PKGDEST}/package/logs/preuninst.log"
    rm -f "/usr/local/etc/services.d/docker_${container_name}.sc"
fi

exit $ret
